### ISSUE TITLE
ipfs-update doesn't work on Windows

### ISSUE THREAD

**Issue by DanielKeep** [ipfs/ipfs-update#32]
I just tried to use ipfs-update to install v0.4.0, and this is what I got:

```
C:\Users\drk>ipfs update --verbose install v0.4.0
daemon check failed: open .ipfs\api: The system cannot find the file specified. fetching go-ipfs version v0.4.0
  - using GOOS=windows and GOARCH=amd64
  - fetching "/ipns/dist.ipfs.io/go-ipfs/v0.4.0/go-ipfs_v0.4.0_windows-amd64.zip"
fetching url: https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v0.4.0/go-ipfs_v0.4.0_windows-amd64.zip
  - writing to C:\Users\drk\AppData\Local\Temp\ipfs-update075339658\go-ipfs_v0.4.0_windows-amd64.zip
  - unpacking zip to "C:\\Users\\drk\\AppData\\Local\\Temp\\ipfs-update518033175\\ipfs-new"
  - extracting binary to tempdir:  C:\Users\drk\AppData\Local\Temp\ipfs-update518033175\ipfs-new
binary downloaded, verifying...
  - running init in '.ipfs\update-staging\test137528673' with new binary
install failed, reverting changes...
ERROR: error initializing with new binary: exec: "C:\\Users\\drk\\AppData\\Local\\Temp\\ipfs-update518033175\\ipfs-new": file does not exist:
```

I checked, and the indicated `ipfs-new` file exists.  It looks like the problem is that it's trying to execute it, but it's doing it in a way that doesn't work unless the file has an `.exe` extension.

(This is doubly frustrating because I already _have_ 0.4.0; it's just that I want to migrate my current settings, but there are no instructions for how to do this other than "run ipfs-update".)

**Comment by whyrusleeping** [comment]
Thanks for the report, we don't test on windows as much as we should.

Since you already have 0.4.0 and you just want to update to the latest release version, a workaround it to go to http://dist.ipfs.io (or since we don't have an https cert for that domain: https://ipfs.io/ipns/dist.ipfs.io ) and download the latest go-ipfs release from there.

**Comment by DanielKeep** [comment]
I already had the actual ipfs binary, but didn't realise fs-repo-migrations was a thing.  All appears to be working now (I mean, aside from ipfs-update :P)

**Comment by zQueal** [comment]
I've also run into this;

    λ ipfs-update install "v0.4.3-rc1"
    fetching go-ipfs version v0.4.3-rc1
    binary downloaded, verifying...
    install failed, reverting changes...
    ERROR: error initializing with new binary: exec: "C:\\Users\\zqueal\\AppData\\Local\\Temp\\ipfs-update141156367\\ipfs-new": file does not exist:

**Comment by whyrusleeping** [comment]
I now have a windows partition on my laptop, assigning this to myself so i can verify this works on windows.

**Comment by Azulan** [comment]
I have the same problem. Probably related to #39 and #46.

**Comment by bogdoslav** [comment]
I developing IPFS installer for Windows and want to include automated updates into it. Please fix this bug, because latest ipfs-update.exe still return same error. Thank you

**Comment by whyrusleeping** [comment]
I managed to fix the "file does not exist issue", but then i immediately run into this:
```
why@DESKTOP-K1JQ69C MINGW64 ~/go/src/github.com/ipfs/ipfs-update (master)
$ ipfs-update.exe --verbose install v0.4.13
daemon check failed: open C:\Users\why\.ipfs\api: The system cannot find the file specified.
fetching go-ipfs version v0.4.13
  - using GOOS=windows and GOARCH=amd64
  - fetching "/ipns/dist.ipfs.io/go-ipfs/v0.4.13/go-ipfs_v0.4.13_windows-amd64.zip"
fetching url: https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v0.4.13/go-ipfs_v0.4.13_windows-amd64.zip
  - writing to C:\Users\why\AppData\Local\Temp\ipfs-update308382786\go-ipfs_v0.4.13_windows-amd64.zip
  - unpacking zip to "C:\\Users\\why\\AppData\\Local\\Temp\\ipfs-update206598319\\ipfs-new.exe"
  - extracting binary to tempdir:  C:\Users\why\AppData\Local\Temp\ipfs-update206598319\ipfs-new.exe
binary downloaded, verifying...
  - running init in 'C:\Users\why\.ipfs\update-staging\test062923961' with new binary
  - running: [C:\Users\why\AppData\Local\Temp\ipfs-update206598319\ipfs-new.exe init]
install failed, reverting changes...
ERROR: error initializing with new binary: exit status 2: panic: CryptAcquireContext: Provider DLL failed to initialize correctly.

goroutine 1 [running]:
gx/ipfs/QmcyaFHbyiZfoX5GTpcqqCPYmbjYNAhRDekXSJPFHdYNSV/go%2euuid.safeRandom(0xc0420107c0, 0x10, 0x10)
        gx/ipfs/QmcyaFHbyiZfoX5GTpcqqCPYmbjYNAhRDekXSJPFHdYNSV/go.uuid/uuid.go:115 +0x73
gx/ipfs/QmcyaFHbyiZfoX5GTpcqqCPYmbjYNAhRDekXSJPFHdYNSV/go%2euuid.NewV4(0x0, 0x0)
        gx/ipfs/QmcyaFHbyiZfoX5GTpcqqCPYmbjYNAhRDekXSJPFHdYNSV/go.uuid/uuid.go:418 +0x6f
gx/ipfs/QmT4PgCNdv73hnFAqzHqwW44q7M9PWpykSswHDxndquZbc/go-libp2p-loggables.Uuid(0xe0ee95, 0x7, 0x1540540)
        gx/ipfs/QmT4PgCNdv73hnFAqzHqwW44q7M9PWpykSswHDxndquZbc/go-libp2p-loggables/loggables.go:35 +0x2d
main.mainRet(0x0)
        github.com/ipfs/go-ipfs/cmd/ipfs/main.go:69 +0xf4
main.main()
        github.com/ipfs/go-ipfs/cmd/ipfs/main.go:64 +0x29
```

Not sure what `CryptAcquireContext` is...

The diff is just:
```diff
diff --git a/lib/install.go b/lib/install.go
index 944dc86..7acba0f 100644
--- a/lib/install.go
+++ b/lib/install.go
@@ -25,8 +25,12 @@ func (i *Install) getTmpPath() (string, error) {
        if err != nil {
                return "", err
        }
+       binname := "ipfs-new"
+       if runtime.GOOS == "windows" {
+               binname += ".exe"
+       }

-       return filepath.Join(tmpd, "ipfs-new"), nil
+       return filepath.Join(tmpd, binname), nil
 }

 func NewInstall(root, target string, nocheck bool) (*Install, error) {
```

**Comment by hsanjuan** [comment]
I think this is not the case anymore. re-open if needed.
